# Generated by Django 5.2.3 on 2025-08-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="gpa",
        ),
    ]
